export const FETCH_BLURBS = "FETCH_BLURBS";
export const SET_USER_WITH_ONLY_AUTH_RES = "SET_CURRENT_USER";
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const SET_EXISTING_USER_WITH_REALTIME_RESPONSE =
  "SET_EXISTING_USER_WITH_REALTIME_RESPONSE";
export const SIGN_OUT = "SIGN_OUT";
